@api = http://localhost:4000/api/users

### CREAR USUARIO
POST {{api}}
Content-Type: application/json

{
    "codigo":"31098221",
    "nombres":"Bienestar2",
    "apellidos":"Zieme",
    "dni":"09819971",
    "email":"bienestaredu2@unmsm.edu.pe",
    "password":"edubienestar2",
    "direccion":"25732 Bartell Creek",
    "telefono":"907936523",
    "sexo":"FEMENINO",
    "rol":"admin"
}

### LISTAR USUARIOS

GET https://nameless-plains-49486.herokuapp.com/api/users
access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDE3MzQwNjU2ODgyMDAxMDM3MDMyNCIsImlhdCI6MTYwNzc0OTM5OSwiZXhwIjoxNjA3ODM1Nzk5fQ.qzCkT5bYPaiKe0VvoX_7d36Rczk5Sm8c4hwB4eJO5nU


### BUSCAR USUARIO POR DNI
GET http://localhost:4000/api/users/06382891


### LOGIN
POST https://nameless-plains-49486.herokuapp.com/api/auth/signin
Content-Type: application/json

{
    "email":"andres.paredes2@unmsm.edu.pe",
    "password":"andres23"
}

### get ficha medica por codigo de usuario
GET http://localhost:4000/api/medic/usuario/18200073

### get ficha medica por id
GET http://localhost:4000/api/medic/5fb4a04e6ccb72517c70e1e4


###
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "email":"unidad.d3ds3434fd@unmsm.edu.pe",
    "password":"bienestaru",
    "nombres":"fdfgv",
    "apellidos":"Malazquez",
    "codigo":"13489093",
    "dni":"78700932",
    "direccion":"dsdds",
    "telefono":"909984321"
}


### crear una ficha médica
POST http://localhost:4000/api/medic/
Content-Type: application/json

{
    "diagnostico":["COVID-19"],
    "tipoSangre":"Apositivo",
    "seguroMedico":{
        "UNMSM":false,
        "MINSA":false,
        "ESSALUD":true
    },
    "anio":"2020",
    "email":"bienestaredu2@unmsm.edu.pe"
}

###charts seguro medico
### UNMSM
GET http://localhost:4000/api/charts/seguro-medico

###
GET http://localhost:4000/api/charts/prueba

###
GET http://localhost:4000/api/charts

