@api = http://localhost:4000/api/users

### CREAR USUARIO
POST {{api}}
Content-Type: application/json

{
    "codigo":"74635102",
    "nombres":"Andres Fernando",
    "apellidos":"Paredes Higuain",
    "dni":"08451009",
    "email":"andres.paredes2@unmsm.edu.pe",
    "password":"andres23",
    "direccion":"25732 Bartell Creek",
    "telefono":"907584923"
}

### LISTAR USUARIOS
GET {{api}}

### BUSCAR USUARIO POR DNI
GET http://localhost:4000/api/users/06382891

### LOGIN
POST http://localhost:4000/api/auth/signin
Content-Type: application/json

{
    "email":"unidad.bienestar20@unmsm.edu.pe",
    "password":"bienestaru"
}
